# Generated by Django 6.0.6 on 2026-06-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
